export const articlelist = [
    {
        article_id: "A001",
        title: "The Future of Iphone",
        publication_date: "15-May-2024",
        content: "Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields...Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields",
        summary: "This article explores the future trends and potential impacts of artificial intelligence on various industries.This article explores the future trends and potential impacts of artificial intelligence on various industries.This article explores the future trends and potential impacts of artificial intelligence on various industries.This article explores the future trends and potential impacts of artificial intelligence on various industries.",
        tags: ["AI", "Technology", "Future"],
        category: "Technology",
        image_link: "/public/assets/gallery/hospitalp10.jpeg",
      },
      {
        article_id: "A001",
        title: "The Future of AIB",
        publication_date: "15-May-2024",
        content: "Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields...Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields",
        summary: "This article explores the future trends and potential impacts of artificial intelligence on various industries.",
        tags: ["AI", "Technology", "Future"],
        category: "Technology",
        image_link: "/public/assets/gallery/Hosptialp10",
      },
      {
        article_id: "A001",
        title: "The Future of AI",
        publication_date: "15-May-2024",
        content: "Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields...Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields",
        summary: "This article explores the future trends and potential impacts of artificial intelligence on various industries.",
        tags: ["AI", "Technology", "Future"],
        category: "Technology",
        image_link: "/public/assets/gallery/Hosptialp10",
      },
      {
        article_id: "A001",
        title: "The Future of AI",
        publication_date: "15-May-2024",
        content: "Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields...Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields",
        summary: "This article explores the future trends and potential impacts of artificial intelligence on various industries.",
        tags: ["AI", "Technology", "Future"],
        category: "Technology",
        image_link: "/public/assets/gallery/Hosptialp10",
      },
      {
        article_id: "A001",
        title: "The Future of AI",
        publication_date: "15-May-2024",
        content: "Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields...Artificial intelligence (AI) is rapidly evolving, with advancements in machine learning, natural language processing, and other fields",
        summary: "This article explores the future trends and potential impacts of artificial intelligence on various industries.",
        tags: ["AI", "Technology", "Future"],
        category: "Technology",
        image_link: "/public/assets/gallery/Hosptialp10",
      },
]

